def ftasGetLicenseErrorsAndWarnings():
  return foGetLicenseCollectionForAllLoadedProducts().ftasGetLicenseErrorsAndWarnings();

from .foGetLicenseCollectionForAllLoadedProducts import foGetLicenseCollectionForAllLoadedProducts;
